version: "3"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5000:5000"
    depends_on:
      - redis
    volumes:
      - ./model:/model
  worker:
    build:
      context: .
      dockerfile: ./queue_handler/Dockerfile
    depends_on:
      - redis
    volumes:
      - ./model:/model
  redis:
    image: redis
    ports:
      - "6379:6379"